### ISSUE TITLE
The app doesn't run

### ISSUE THREAD

**Issue by anthonysalvato3** [l3a0/boron#1]
After a clone and npm install, npm start gives the following error:

npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! client@0.1.0 start: `react-app-rewired start`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the client@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by l3a0** [comment]
Could you please include the full log of error?

**Comment by anthonysalvato3** [comment]
Thanks for the quick response.
[2020-03-14T21_48_06_199Z-debug.log](https://github.com/l3a0/boron/files/4333387/2020-03-14T21_48_06_199Z-debug.log)

**Comment by l3a0** [comment]
Are you running this in Windows? I am running this inside Windows Subsystem for Linux.

See:
https://blog.baowebdev.com/2019/10/using-openzeppelin-tutorial-starter-kit/

**Comment by anthonysalvato3** [comment]
Yes, I am using Windows. I will look into using WSL.
